title: Madison Brading # your name (or website title) here
logo: "/images/Screen Shot 2020-12-16 at 11.03.48 PM.png" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I'm a second year student at the University of Southern California, and I'm studying Computer Science and Business Administration. I'm an 
  fast learner, a team player, and am interested in learning more about the complex world we live in.
  <br><br>
  <a href="https://www.linkedin.com/in/madisonbrading/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-H5JWWF59SD # your Google Analytics tracking ID here
