title: Madison Brading # your name (or website title) here
logo: "/images/headshot.jpg" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Hi! I’m currently a sophomore at the USC Viterbi School of Engineering majoring in computer science and business. I’m currently a student advocate for USC’s health center program VOICE 
  and I am a member of AIM consulting.I'm a fast learner, a team player, and am interested in learning more about the complex world we live in.
  <br><br>
  <a href="https://www.linkedin.com/in/madisonbrading/">View My LinkedIn Profile</a>
  
theme: jekyll-theme-minimal
google_analytics: G-H5JWWF59SD # your Google Analytics tracking ID here
